services:
  auth:
    build: .
    ports:
      - "3000:3000"
    env_file:
        .env
    environment:
      RUST_LOG: info
      DATABASE_URL: sqlite:///app/data/auth_service.db
    volumes:
        - "auth-data:/app/data"
    restart: unless-stopped

volumes:
  auth-data: